export { resolveAttackConfiguration, resolvePrimaryPlayerMeleeAttack } from './attackConfiguration'
export type {
  AttackConfiguration,
  AttackConfigurationIssue,
  AttackResolution,
  CriticalEligibilityFailure,
  DamageSourceConfiguration,
  DeferredPlayerAttackConfiguration,
  DeferredPlayerAttackFamily,
  InvalidAttackResolution,
  NoOperationAttackResolution,
  OmittedVelocityOperationDiagnostic,
  PlayerCriticalEligibilityState,
  PlayerMeleeAttackDiagnostics,
  PlayerMeleeMechanicsParameters,
  PrimaryPlayerMeleeAttackConfiguration,
  SuccessfulAttackResolution,
  UnsupportedAttackResolution,
} from './attackConfiguration'
export { foldAttributeModifiers, je26_2AttributeDefinitions } from './attributes'
export { matchBlockDefinitions, resolveBlock, resolveJe26_2Block } from './blockResolution'
export type {
  BlockDefinitionMatchResult,
  BlockEligibility,
  BlockItemClassification,
  BlockMembershipEntry,
  BlockMembershipIndex,
  BlockResolutionDiagnostic,
  BlockResolutionOutcome,
  BlockResolutionResult,
} from './blockResolution'
export {
  foldMatchingDefinitions,
  resolveArchetype,
  toCubeMechanicsProperties,
  toResolvableCubeDefinition,
  toTrajectoryAssumptions,
} from './cubeProperties'
export {
  copyCurrentResolvedCubeProperties,
  createDefaultCubePropertySelectionState,
  resolveCubePropertySelection,
  selectCubePropertyArchetype,
  selectCubePropertyBlock,
  selectCubePropertyMode,
  updateCustomCubeProperty,
} from './propertySelection'
export type {
  CubePropertyMode,
  CubePropertySelectionDiagnostic,
  CubePropertySelectionResolution,
  CubePropertySelectionSource,
  CubePropertySelectionState,
  CustomCubePropertyFormState,
  CustomCubePropertyWorkingCopy,
  CustomPropertyDiagnostic,
  CustomPropertyField,
  CustomPropertyInput,
  LockedCubePropertyMode,
} from './propertySelection'
export type {
  ActiveModifiersByOperation,
  AttributeActionGroup,
  AttributeCandidateInput,
  AttributeDefinition,
  AttributeFoldDiagnostic,
  AttributeFoldResult,
  AttributeModifierAction,
  AttributeModifierActionStatus,
  AttributeResolution,
  CubePropertyFoldStep,
  NumericRepresentation,
  ResolvableAttributeModifier,
  ResolvableCubeDefinition,
  ResolvedContactDamage,
  ResolvedCubeProfile,
  ResolvedExplosionData,
  ResolvedKnockbackModifiers,
  ResolvedNumericSelection,
  ResolvedSoundSettings,
  SourcedAttributeModifier,
} from './types'
